### ISSUE TITLE
Script never terminates unless at least one match is found

### ISSUE THREAD

**Issue by Treeston** [rngchan/sun-moon-rng#13]
Line 334:
`while not results or len(results) < params["nresults"] and tries < 10000:`

should be:
`while (not results or len(results) < params["nresults"]) and tries < 10000:`

**Comment by rngchan** [comment]
That is intentional. There has been many complaints on results file being empty, so I've decided to leave it be until at least one result is found, to avoid confusion with why the results is empty. A solution would be to put the timeout as a parameter, but with the amount of things in the config already it seems simpler to just leave it be to avoid user confusion.

**Comment by Treeston** [comment]
Alright, makes sense. Maybe a short output message like
`No results found after timeout (10000 tries), continuing... (Ctrl-C to stop)`
would help clarity here?

**Comment by rngchan** [comment]
Perhaps, I'll think of which approach is better and patch it up along with the problems pointed out in the other issue.

**Comment by rngchan** [comment]
Should be resolved as of version 0.10.5. The script now prints a warning message every 20000 seeds, giving instructions on how to terminate it if the user wants to stop looking for results.
