### ISSUE TITLE
ERROR: Invalid Ratio For Child

### ISSUE THREAD

**Issue by Ed1004** [rngchan/sun-moon-rng#16]
I tried looking through the closed Issues but even the solution someone had for my problem didn't work for me I have the gender ratio put in right but I keep getting a invalid ratio for child error can you please help me this is my config.txt and my results.txt
[config.txt](https://github.com/rngchan/sun-moon-rng/files/715120/config.txt)
[results.txt](https://github.com/rngchan/sun-moon-rng/files/715121/results.txt)

**Comment by bryanbcheng** [comment]
The reason is you deleted a return before:

```
======================
     OTHER OPTIONS    
======================
```
So just add an extra line after ESV: [].

The code uses the line number of parse the config file so by deleting the line, it's trying to process Masuda line as the gender ratio line, hence the error.

This is the correct config file:
[config.txt](https://github.com/rngchan/sun-moon-rng/files/715931/config.txt)

Here is the outputted results for you:
[results.txt](https://github.com/rngchan/sun-moon-rng/files/715932/results.txt)

**Comment by rngchan** [comment]
Thanks for clarifying the issue bryan, this seems to be a recurrent issue with the config file. I'll include a \r character on every line for the config sample so that Windows users won't get screwed by notepad. Closing this for now.
