### ISSUE TITLE
No results file

### ISSUE THREAD

**Issue by Zorntag** [rngchan/sun-moon-rng#4]
I can't produce a results.txt file when I run rng-abuse. Instead, two files called "pokemons.pyc" and "tinymt.pyc" are created. They don't do anything either. Any advice? I'm probably doing something wrong with the config.txt file, but I've tried different options with it and none of them is working.

**Comment by rngchan** [comment]
Hi there, the .pyc files are files created by python that shouldn't do anything very useful as far as getting your results is concerned. As for you not getting any results.txt, that is a very odd occurence. If possible, can you give some detail on what OS you're in, what python version you have installed and sharing your config file? Thanks in advance, and thanks for using the tool!

**Comment by Zorntag** [comment]
I am using Windows 7 Ultimate and Python 2.7.12.

**Comment by rngchan** [comment]
Do you have all the .py files in the same directory as your python executable? Those should be:

```
tinymt.py
pokemons.py
rng-abuse.py
```
The main script is dependent on those other two, so you need to move them around together for things to work properly. I'm not sure what could be going wrong, so if putting everything in the same directory and running still doesn't work, could you please attach your config.txt file?

**Comment by Zorntag** [comment]
All three files are there. I've tried a different computer with Windows 10 and still nothing. I'm pretty sure the problem has to be the config file. I hope so, since silly mistakes are the easiest to fix!
[config.txt](https://github.com/rngchan/sun-moon-rng/files/668493/config.txt)

**Comment by rngchan** [comment]
So, looking at the config file, it seems that some lines are overlapping with each other, when each parameter should be on its own line:

```
ABILITY SLOT: 1NATURE: Hardy
SHINY: Y======================
SAME SPECIES: NSHOW THIS MANY RESULTS: 40
```

I'm attaching a fixed version, you can try downloading it and seeing if it works.

[config.txt](https://github.com/rngchan/sun-moon-rng/files/668842/config.txt)

**Comment by Zorntag** [comment]
OK, your file produced a results file just fine, so the problem seemed to be the config file. Since I've been playing the game in the last hours I've extracted my save again to check my seed. According to PKHeX, I now have different seed and TSV values. I've edited those values in the file you sent me and it produces a results file (yay, advance!), but it's empty...

**Comment by rngchan** [comment]
This seems to be a general point of confusion, it seems I should approach this differently.

The reason the results file is empty is because the script did not find an egg that matched your config within 10000 frames of your seed. This means that an egg that matches your config exists, but it's too far ahead.

I will update the script to always show at least 1 result, even if it is very far into the RNG. In addition, I'll make it so that errors with the configuration file are written to results.txt.

In the mean time, you can try the following:
* Open the rng-abuse.py script in any text editor (that isn't notepad)
* Go to line 315, where it limits the search to 10000 frames
* Change the 10000 in that line to a bigger number (I believe 50000 should be enough)
* Try running it again

**Comment by Zorntag** [comment]
Gosh, 15435 eggs. Talk about unlucky. At least I know how to make it work now. Thanks a lot for your help!

**Comment by rngchan** [comment]
No problem, good luck on your egg hunts! I'm going to implement those changes commented on my post so that this confusion as to why the file isn't generated doesn't happen any more (or at least as often as it does happen now). Closing this issue for now since the problem was resolved.

**Comment by earthchie** [comment]
15435 egss?!

I have 13,313 eggs to go. now I feel better lol
