### ISSUE TITLE
Feature Request: filter for extra TSV matches

### ISSUE THREAD

**Issue by shadowofdarkness** [rngchan/sun-moon-rng#5]
Could you please add a option filter results for potential TSV matches for different games.
Unlike the generating games TSV match that would stop pulling PID from the 8 RNG tries early if a match is found, they would have to have to be only shown if the TSV matches the ESV that is used in the final generated egg.

This would help increase the amount of shinies that I can get. Since at times it can be long stretches before a normal TSV match for my Moon game. But with this I would be able to find eggs that if traded to my other Sun game would hatch shiny. A example being that currently in Moon my next Moon match is in A-85 R-20 but I'll have a earlier match to my Sun save a A-52 R-22

Currently I can find them by doing searches in the results but it would be nice to have a filter  where I can easily have a list of multiple extra TSV's.

**Comment by rngchan** [comment]
Hi there, thanks for your suggestion!

I never really considered the case for people with access to multiple TSVs, but now that you brought this up there's certainly a lot of reason to implement it! I spent some time thinking about how to approach this, and here are some details, see if this is more or less how you thought things would go down:

* In addition to the TSV parameter, add a ESV one that contains a list of interesting ESV values
* When eggs are generated that do not match the TSV, consider them a valid result if they match one of the ESV values given

The configuration file would then look like this:

```
TSV: 3030
ESV: [1239, 3000, 3456]
```

And thus, eggs will be considered shiny if the TSV matches, but will be considered potential shinies if any ESV matches. The reason for this distinction is because when generating eggs, the game checks for shininess comparing the egg's ESV to your TSV, and it stops rerolling PIDs if it matches. This way, I need to know which is your TSV and which are possible alternate ESVs that can be valid, given you have access to trading.

I'll start working on it as soon as possible, if I missed anything or something is poorly explained please let me know.

**Comment by shadowofdarkness** [comment]
That's exactly what I was imagining. I knew about the pid rolls stopping and you even had clearer wording then me about it.

**Comment by rngchan** [comment]
Feature is now supported as of version 0.10.1, works as described above. More info on the updated config explanation and readme.
