### ISSUE TITLE
Seed output missing 0

### ISSUE THREAD

**Issue by brutalgg** [rngchan/sun-moon-rng#6]
Hello, 
I seem to have found a bug when it comes to outputting the next seed.
The script generates seed a7e9069aa40f94b1cea8696f60e63e0 which is 31 characters in length. I manually verified the seed and it resulted in A7E9069AA40F94B10CEA8696F60E63E0. As you can see the 0 before the CEA in the script output appears to be missing. Wanted to pass this information along.

**Comment by rngchan** [comment]
You mean when using the `getStateAsHex` method from TinyMT class? Seems to be an issue with python not writing the leading zeroes when calling the `hex()` function. It seems to be the only place being affected by this, since it's the only place I concatenate the status[3]~[0] numbers into one big string.

Thanks, going to patch it up now.

**Comment by rngchan** [comment]
Well, I patched it up and it should be working as of version 0.10.2.
