### ISSUE TITLE
Not so much an issue, but our threads are ghost, so here's a question.

### ISSUE THREAD

**Issue by RoLau** [rngchan/sun-moon-rng#9]
Would it be possible, since we'd know the current seed, to make an additional script to advance the seed X number of eggs if you want to take on a breeding project?

**Comment by rngchan** [comment]
While it certainly is possible, there are a number of factors that would get in the way of such a script:

* Changing parents from, say, any species with a ditto to two mons with the same species would offset the seed
* The same goes for switching items around, removing destiny know mid project would mess things up
* There's also removing Masuda Method, which could, again, offset the seed

If you're going to advance your seed based on the number of generated eggs, you need to make sure the parents and items are always the same, otherwise things will be off, thus you'd need to keep track of how many eggs you generated before switching configs.

You can already do this, sort of, with this script. Set your config file's child parameters to "Anything" on every field, and keep IVs 0-31, and you'll get a list of all possible eggs. You can specify how far ahead you want to look, too. That way, if you want to know how far ahead you will be after accepting 5 eggs in a row with this configuration, just ctrl+f "Accept 5 eggs", and you'll go exactly to the egg you'd have just accepted.

**Comment by RoLau** [comment]
Ah, that's pretty cool. I didn't think to use the results file that way. I miss the threads ;_;
